### ISSUE TITLE
How to do event handling for android and iOS in react native's new architecture for fabric components?

### ISSUE THREAD

**Issue by BraveEvidence** [slavikdenis/rn-new-architecture#1]
Sorry to open this as an issue, can you help me this https://stackoverflow.com/questions/72981626/how-to-do-event-handling-for-android-and-ios-in-react-natives-new-architecture

**Comment by slavikdenis** [comment]
Hello.

Thanks for opening this issue. I ran into this one myself and unfortunately, I didn't figure it out yet.
As you could maybe see, I tried to define the functions in Typescript, which I'm pretty sure it's not working *yet*.

Try to check out react-native-screens from Software Mansion. They already support the new architecture in their library and they documented their process.

See for example this component:
https://github.com/software-mansion/react-native-screens/blob/main/src/fabric/ScreenNativeComponent.js

Blog post:
https://blog.swmansion.com/introducing-fabric-to-react-native-screens-fd17bf18858e

If I manage to make it work in the near future, I will let you know :)

Thanks again

EDIT: I also posted your StackOverflow question to my colleagues, maybe they have dealt with it already :)
